# --- Sitio ---
title: "ChatTDP"
description: "Tu asistente virtual para resolver cualquier duda de la Liga TDP Varonil y Femenil"
email: soporte@whistletime.com.mx

# IMPORTANTE: cambia esta línea cuando muevas de dominio
# Ejemplos:
#   producción con subdominio: https://chattdp.whistletime.com.mx
#   producción en dominio raíz: https://whistletime.com.mx
#   (en previews de Cloudflare no pasa nada si queda así; usa siempre | relative_url en templates)
url: "https://chattdp.pages.dev"
baseurl: ""   # vacío si sirves en raíz o subdominio directo

theme_color: "#049445"   # verde identidad
logo: assets/images/icon.png

languages: ["es"]
ampdir: amp    # si no usas AMP, puedes quitar esta línea

# Social (para jekyll-seo-tag)
twitter:
  username: whistletime   # cámbialo si aplica
social:
  name: "Whistle Time"
  links:
    - https://whistletime.com.mx

# SEO canónico y URLs limpias
permalink: pretty

# --- Plugins ---
# Si te falla la build en Cloudflare, comenta los que no uses (p. ej. amp-jekyll u octopress-minify-html)
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html   # si da error, comenta esta línea
  - amp-jekyll              # si no usas AMP, comenta esta línea

# --- Defaults útiles ---
defaults:
  - scope:
      path: ""          # todo el sitio
    values:
      lang: "es"        # <html lang="es">
      image: "/assets/images/icon.png"   # imagen por defecto para og:image
      layout: default

# --- Enlaces del proyecto (opcional, solo si todavía los usas en algún include) ---
github: https://github.com/sandoche/Mobile-app-landingpage-template

# --- Analytics / Webmaster (opcional) ---
# webmaster_verifications:
#   google: TU_CODIGO
# google_analytics: G-XXXXXXXXXX

# --- Excluir del build ---
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
