name: ChatTDP
description: "Asistente virtual para equipos, árbitros y aficionados de la Liga TDP Varonil y Femenil."
full_description: >
  <p><strong>ChatTDP</strong> es tu asistente virtual especializado en la Liga TDP, diseñado para responder cualquier duda de forma rápida y confiable.</p>

  <p>Consulta reglas, procedimientos y situaciones de competencia sin buscar en documentos extensos. Disponible para la rama Varonil y Femenil.</p>

  <p><strong>Con ChatTDP puedes:</strong></p>
  <ul>
    <li>📚 Consultar el reglamento de competencia en segundos.</li>
    <li>🚑 Conocer normas como la tolerancia de ambulancia o sobre situaciones atípicas.</li>
    <li>📝 Generar oficios oficiales (por ejemplo, nombrar responsable de banca).</li>
    <li>📱 Acceder desde Android, iOS.</li>
    <li>⚡ Usar una interfaz rápida, intuitiva y siempre actualizada.</li>
  </ul>

  <p>¿Sin responsable de banca? ¿Dudas sobre sustituciones u obligaciones? ¿Necesitas un oficio oficial?<br>
  ChatTDP lo resuelve en segundos.</p>

  <p><strong>Olvídate de buscar por palabras en PDFs:</strong> con ChatTDP basta con preguntarle al asistente virtual, incluso sin acentos o con faltas de ortografía, y obtendrás la respuesta al instante.</p>

android: https://telegra.ph/Replace-this-link-07-23
iOS: https://telegra.ph/Replace-this-link-07-23
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - login.png
  - chat.png
  - chatFeme.png
  - pdfView.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://whistletime.com.mx/
    image: icon_whistle_time.png

terms_pdf: /assets/docs/terminos-y-condiciones-chattdp.pdf
privacy_pdf: /assets/docs/aviso-de-privacidad-chattdp.pdf

support_email: soporte@whistletime.com.mx
delete_form_endpoint: https://formspree.io/f/mkgzyqwl
