name: ChatTDP
description: "Tu asistente virtual para resolver cualquier duda de la Liga TDP Varonil y Femenil"
full_description: >
  <p>ChatTDP es tu asistente virtual especializado en la Liga TDP, tanto en su rama Varonil como Femenil.</p>

  <p>Responde de forma rápida, precisa y sencilla cualquier pregunta sobre el reglamento, procedimientos y situaciones de competencia.</p>

  <p><strong>Con ChatTDP podrás:</strong></p>
  <ul>
    <li>Consultar dudas del reglamento de competencia en segundos.</li>
    <li>Conocer reglas como la tolerancia de la ambulancia y la normativa sobre responsables de banca.</li>
    <li>Generar oficios/solicitudes (p. ej., para nombrar responsable de banca).</li>
    <li>Acceder desde Android y iOS.</li>
    <li>Usar una interfaz intuitiva con respuestas rápidas y actualizadas.</li>
  </ul>

  <p>¿Sin responsable de banca? ¿Dudas sobre sustituciones u obligaciones de equipo? ¿Necesitas un oficio oficial?<br>
  ChatTDP puede ayudarte con eso… y más.</p>

android: https://telegra.ph/Replace-this-link-07-23
iOS: https://telegra.ph/Replace-this-link-07-23
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - login.png
  - chat.png
  - chatFeme.png
  - pdfView.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://whistletime.com.mx/
    image: icon_whistle_time.png